#import "React/RCTBridgeModule.h"

// Import the autogenerated Swift header


@interface RCT_EXTERN_MODULE(CreateWallet, NSObject)

// Bridge methods
RCT_EXTERN_METHOD(
  generateMnemonics:(RCTResponseSenderBlock)successCallback
  errorCallback:(RCTResponseSenderBlock)errorCallback
)

RCT_EXTERN_METHOD(
  generateKeysForAllBlockchains:(NSString *)mnemonics
  successCallback:(RCTResponseSenderBlock)successCallback
  errorCallback:(RCTResponseSenderBlock)errorCallback
)

@end
